services:
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3002:3002"
    volumes:
      - ./frontend:/app/frontend
    depends_on:
      - backend
    networks:
      - app-network
    
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app/backend
    depends_on:
      - database
    networks:
      - app-network
    
  database:
    image: postgres:latest
    container_name: database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=database
    depends_on:
      - database
    networks:
      - app-network

volumes:
  postgres_data:
    name: postgres_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/db

networks:
  app-network:
    driver: bridge